export { default as SidebarDesktopIcon } from './bg-sidebar-desktop.svg'
export { default as SidebarMobileIcon } from './bg-sidebar-mobile.svg'
export { default as AdvancedIcon } from './icon-advanced.svg'
export { default as ArcadeIcon } from './icon-arcade.svg'
export { default as CheckMarkIcon } from './icon-checkmark.svg'
export { default as ProIcon } from './icon-pro.svg'
export { default as ThankYouIcon } from './icon-thank-you.svg'